#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer output_block
{
    float16_t values[];
} output_data;

const float16_t constants[3] = float16_t[3](
    float16_t(0.0), float16_t(1.0), float16_t(2.0));

void main()
{
    output_data.values[gl_GlobalInvocationID.x] =
        constants[gl_GlobalInvocationID.x % 3];
}
