// Copyright 2026 nihui
// SPDX-License-Identifier: Apache-2.0

#version 450
#extension GL_ARB_gpu_shader_fp64 : require

layout(local_size_x = 4, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer
{
    double values[];
} input_buffer;

layout(set = 0, binding = 1, std430) writeonly buffer OutputBuffer
{
    double values[];
} output_buffer;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    double x = input_buffer.values[i];
    dvec4 c = dvec4(x);
    dvec4 a = c + dvec4(0.0, 1.0, 2.0, -3.0);
    dvec4 b = dvec4(double(gl_LocalInvocationID.x)) + dvec4(2.0, 3.0, 5.0, -7.0);
    c = a * c + b;
    output_buffer.values[i] = (c.x + c.y) + (c.z + c.w);
}
