// Copyright 2026 nihui
// SPDX-License-Identifier: Apache-2.0

#version 450
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer InputBuffer
{
    u16vec4 values[];
} input_buffer;

layout(set = 0, binding = 1, std430) writeonly buffer OutputBuffer
{
    u16vec4 values[];
} output_buffer;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    u16vec4 value = input_buffer.values[i];
    uint packed = packUint2x16(value.xy);
    u16vec2 unpacked = unpackUint2x16(packed);
    output_buffer.values[i] = u16vec4(unpacked, value.zw) + u16vec4(uint16_t(1));
}
