#!/usr/bin/env python3

# Copyright 2026 nihui
# SPDX-License-Identifier: Apache-2.0

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE_MANIFEST = ROOT / "src/source_manifest.txt"


def read_source_manifest():
    groups = {"translator": [], "driver": []}
    entries = []
    driver_seen = False
    for line_number, line in enumerate(
        SOURCE_MANIFEST.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split(None, 1)
        if len(fields) != 2 or fields[0] not in groups:
            raise ValueError(
                "invalid source manifest entry at {}:{}".format(
                    SOURCE_MANIFEST, line_number
                )
            )
        group = fields[0]
        relative = Path(fields[1])
        if group == "translator" and driver_seen:
            raise ValueError(
                "translator entry appears after driver entry at {}:{}".format(
                    SOURCE_MANIFEST, line_number
                )
            )
        if group == "driver":
            driver_seen = True
        if not (ROOT / relative).is_file():
            raise ValueError(
                "source manifest path does not exist at {}:{}: {}".format(
                    SOURCE_MANIFEST, line_number, relative
                )
            )
        groups[group].append(relative)
        entries.append((group, relative))
    return entries, groups

def is_manifest_include(relative, line, manifest_files):
    prefix = '#include "'
    if not line.startswith(prefix) or not line.endswith('"'):
        return False
    include = Path(line[len(prefix) : -1])
    candidates = (
        (ROOT / relative).parent / include,
        ROOT / "src" / include,
        ROOT / "include" / include,
    )
    return any(candidate.resolve() in manifest_files for candidate in candidates)


def source_lines(relative, manifest_files):
    lines = []
    for line in (ROOT / relative).read_text(encoding="utf-8").splitlines():
        if line == '#include "vulkan_procs.inc"':
            lines.extend(
                (ROOT / "src/vulkan_procs.inc")
                .read_text(encoding="utf-8")
                .splitlines()
            )
        elif not is_manifest_include(relative, line, manifest_files):
            lines.append(line)
    return lines


def render() -> str:
    entries, _ = read_source_manifest()
    manifest_files = {(ROOT / relative).resolve() for _, relative in entries}
    chunks = [
        "// Generated by tools/amalgamate.py. Do not edit.\n"
        "// Copyright 2026 nihui\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
    ]
    driver_guard_open = False
    for group, relative in entries:
        if relative.suffix == ".inc":
            continue
        if group == "driver" and not driver_guard_open:
            chunks.append(
                "\n#if defined(NCNN_MOMOTEN_TRANSLATOR_ONLY) && "
                "!defined(MOMOTEN_TRANSLATOR_ONLY)\n"
                "#define MOMOTEN_TRANSLATOR_ONLY 1\n"
                "#endif\n\n"
                "#ifndef MOMOTEN_TRANSLATOR_ONLY\n"
            )
            driver_guard_open = True
        lines = source_lines(relative, manifest_files)
        chunks.append(
            "\n// ---- begin {} ----\n{}\n// ---- end {} ----\n".format(
                relative.as_posix(), "\n".join(lines), relative.as_posix()
            )
        )
    if driver_guard_open:
        chunks.append("\n#endif // MOMOTEN_TRANSLATOR_ONLY\n")
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the momoten single-file distribution")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--output", type=Path)
    group.add_argument("--check", type=Path)
    group.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    generated = render()
    if args.stdout:
        sys.stdout.write(generated)
        return 0
    if args.check:
        if not args.check.exists() or args.check.read_text(encoding="utf-8") != generated:
            print("momoten amalgamation is stale; regenerate {}".format(args.check), file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
